### ISSUE TITLE
[Security] Bump Pillow to  >= 9.0.0

### ISSUE THREAD

**Issue by wgranger** [zooniverse/theia#103]
Multiple security updates have been tagged over the past few months; however, dependabot isn't opening an automated PR. These are found in this repo under Security - Dependabot alerts - [Pillow](https://github.com/zooniverse/theia/network/alert/Pipfile.lock/pillow/open). Info for the most recent bump is found [here](https://github.com/advisories/GHSA-43fq-w8qq-v88h), and they are all moderate vulnerabilities.

**Comment by eatyourgreens** [comment]
Updating the version number because there are critical vulnerabilities in Pillow prior to version 9.
