### ISSUE TITLE
Unable to build docker image using wsl

### ISSUE THREAD

**Issue by andy-waxman** [zooniverse/theia#171]
I have tried to build the docker image from the production-release branch and the master branch on Ubuntu 20 with Windows Subsystem for Linux on Windows 10. It errors out during the RUN pip install --system --dev command with the following output.

#15 12.48 [pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
#15 12.48 [pipenv.exceptions.InstallError]:
#15 12.48 [pipenv.exceptions.InstallError]:   × python setup.py egg_info did not run successfully.
#15 12.48 [pipenv.exceptions.InstallError]:   │ exit code: 1
#15 12.48 [pipenv.exceptions.InstallError]:   ╰─> [6 lines of output]
#15 12.48 [pipenv.exceptions.InstallError]:       Traceback (most recent call last):
#15 12.48 [pipenv.exceptions.InstallError]:         File "<string>", line 36, in <module>
#15 12.48 [pipenv.exceptions.InstallError]:         File "<pip-setuptools-caller>", line 34, in <module>
#15 12.48 [pipenv.exceptions.InstallError]:         File "/tmp/pip-install-aan_wuvg/libtiff_0d9c20552b544bab8055c4d789cc4a31/setup.py", line 77, in <module>
#15 12.48 [pipenv.exceptions.InstallError]:           from numpy.distutils.core import setup, Extension
#15 12.48 [pipenv.exceptions.InstallError]:       ModuleNotFoundError: No module named 'numpy'
#15 12.48 [pipenv.exceptions.InstallError]:       [end of output]
#15 12.48 [pipenv.exceptions.InstallError]:
#15 12.48 [pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
#15 12.48 [pipenv.exceptions.InstallError]: error: metadata-generation-failed
#15 12.48 [pipenv.exceptions.InstallError]:
#15 12.48 [pipenv.exceptions.InstallError]: × Encountered error while generating package metadata.
#15 12.48 [pipenv.exceptions.InstallError]: ╰─> See above for output.
#15 12.48 [pipenv.exceptions.InstallError]:
#15 12.48 [pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.
#15 12.48 [pipenv.exceptions.InstallError]: hint: See above for details.

**Comment by yuenmichelle1** [comment]
closed with #172
